name: Ruby

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    # If we are merging to master we run
    # the suite without mocking external requests
    - if: github.ref == 'refs/heads/master'
      run: BYPASS_VCR=true bundle exec rake
    # Any other case we run our task without
    # bypassing VCR cassettes
    - if: github.ref != 'refs/heads/master'
      run: bundle exec rake
